24 card component
athena-server/athena-server.github.io pull request #26
Opened 2024-12-15 17:48 UTC by Nandana-Neo

2024-12-15 18:02 UTC, th3bossc requested changes

2024-12-15 18:02 UTC, th3bossc commented on src/components/Card/index.tsx
> +import { alumniSans, geo } from "@/fonts";
if geo is not being used remove it from imports

2024-12-15 18:02 UTC, th3bossc commented on src/components/Card/index.tsx
> +/*
remove these comments if all of them are being followed

2024-12-15 18:02 UTC, th3bossc commented on src/components/Card/index.tsx
> +    const { email, linkedin, github } = socials || {};
i have extracted email, linkedin and github, so everywhere you are currently using socials.email, socials.linkedin, you can directly use these variables

2024-12-15 18:02 UTC, th3bossc commented on src/components/Card/index.tsx
> +                <div className="absolute bottom-0 h-1/2 w-full bg-[radial-gradient(circle_at_bottom_left,_#3F56E9_0%,_transparent_35%)] pointer-events-none z-10"></div>
preferablly use <div /> syntax for empty containers instead of <div> </div>

2024-12-15 18:02 UTC, th3bossc commented on src/components/Card/index.tsx
> +                            <a href={`mailto:${socials.email}?`} >
Why is there a question mark after $[socials.email} ?

2024-12-15 21:05 UTC, NailaFathima approved these changes

2024-12-16 07:05 UTC, th3bossc approved these changes

2024-12-16 07:05 UTC, merged